name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Start Xvfb
      run: Xvfb :99 &
    - name: Run tests with Maven
      run: mvn -B test
      env:
        DISPLAY: :99
        WDM_GITHUBTOKENNAME: ${{ secrets.WDM_GITHUBTOKENNAME }}
        WDM_GITHUBTOKENSECRET: ${{ secrets.WDM_GITHUBTOKENSECRET }}
  scan:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Scan code with SonarCloud
      run: >
        mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        -Pcoverage
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.organization=BoniGarcia
        -Dsonar.projectKey=bonigarcia-github
        -Dsonar.projectName=WebDriverManager
        -Dsonar.scm.disabled=true
      env:
        GITHUB_TOKEN: ${{ secrets.WDM_GITHUBTOKENSECRET }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
